### ISSUE TITLE
`sentio gen` having errors with Fuel ABI

### ISSUE THREAD

**Issue by dmihal** [sentioxyz/sentio-sdk#964]
* forc 0.63.5
* @sentio/cli 2.21.0
* @sentio/sdk 2.43.0

Running `sentio gen` gives the following error:

```
code gen error TypeError: Cannot read properties of undefined (reading 'find')
    at codegenInternal (sentio_indexer/node_modules/@sentio/sdk/lib/fuel/codegen/codegen.js:84:59)
```

The line in question is this:

```typescript
const metadataTypeId = abi.rawContents.concreteTypes.find((t) => t.concreteTypeId == logType.concreteTypeId)?.metadataTypeId;
```

The ABI ingested _is_ the new version of the ABI (which contains `concreteTypes`), however when I inserted a log into this code to log `abi.rawContents`, it's showing the old version of the ABI (without `concreteTypes`). I believe the library is probably downgrading the ABI before reaching this stage.

**Comment by spacedragon** [comment]
it should be fixed, closing
